### Dynamics model parameters for G500

### Simulation Time Properties
dolphin/dynamics/period: 0.001
dolphin/dynamics/uwsim_period: 0.005 # Publish rate set at 200 Hz

### Simulated IMU Properties
dolphin/imu/period: 0.0025                # Publish rate set at 400 Hz
dolphin/imu/quaternion_std: 0.000000001        # Standard Deviation on euler Measurement
dolphin/imu/omega_std: 0.002               # Standard Deviation on Angular Velocity Measurement
dolphin/imu/acceleration_std: 0.01         # Standard deviation on Linear Acceleration

### Inertia Properties
dolphin/dynamics/mass: 0.432
dolphin/dynamics/gravity_center: [0.0, 0.0, -0.002] # TODO: fix, should be w.r.t. to rB
dolphin/dynamics/buoyancy_center: [0.0, 0.0, 0.0] # TODO: fix this should remain zero but rG should change
dolphin/dynamics/g: 9.81
dolphin/dynamics/radius: [.05, .06, .07]
#dolphin/dynamics/tensor: [0.000000001, 0.0,0.0 , -1e-11, 0.0, 0.0, 0.0, 0.000000001, 0.0]
# Tensor values based on Solidworks values Lxx etc
dolphin/dynamics/tensor: [410461e-9, 431e-9, -11631e-9, 431e-9, 338994e-9, -15e-9, -11631e-9, -15e-9, 546986e-9]

### Damping Properties
dolphin/dynamics/damping: [.0, .0, .0, -0.05, -0.05, -0.05]
dolphin/dynamics/quadratic_damping: [-0.05, -0.05, -0.05, -0.05, -0.05, -0.05]
dolphin/dynamics/dzv: 0.05
dolphin/dynamics/dv: 0.35
dolphin/dynamics/dh: 0.4
dolphin/dynamics/density: 1000.0

### Actuator Properties
dolphin/num_actuators: 4
#Actuator kF coefficient (Thrust to Speed relationship)
dolphin/dynamics/actuators_kf: .000009
#Actuator kM coefficient (Thrust to Speed relationship)
dolphin/dynamics/actuators_km: .0000009
#Actuator kV coefficient (Motor KV rating)
dolphin/dynamics/actuators_kV: 4300
#Actuator refV coefficient (Nominal Battery Voltage V)
dolphin/dynamics/actuators_reference_voltage: 7.4
#Actuator load factor (reduction from rated kV under load)
dolphin/dynamics/actuators_load_factor: 0.1
#Actuators acting radius (meters) TODO: VERIFY
dolphin/dynamics/actuators_radius: 1
#Actuator time constant for first order actuator dynamic model: TODO: ESTIMATE
dolphin/dynamics/actuators_tconst: .002
#Inputs higher than actuators_maxsat will saturate to actuators_maxsat
dolphin/dynamics/actuators_maxsat: [1, 1, 1, 1]
#Inputs below actuators_minsat will saturate to actuators_minsat
dolphin/dynamics/actuators_minsat: [-1, -1,  -1, -1]
# Actuator Direction Inversion
dolphin/dynamics/actuators_inversion: [1, 1,  -1, -1]

### Topics
dolphin/dynamics/topic_name: "/dataNavigator"
dolphin/dynamics/external_force_topic: "/dolphin/ForceSensor"
dolphin/dynamics/frame_id: "/dolphin/shell"


### Initialization
# Meters and Rads [X, Y, Z, Roll, Pitch, Yaw] TODO: Get it back from the other launch file
# TODO: How do I incorporate the vehicle model into the simulation?
dolphin/dynamics/initial_pose: [-1.0, 1.0, 4.0, 0, 0, 0] #[3.0, 1.1, 2.8, 0, 0, 3.14]
dolphin/dynamics/initial_velocity: [0, 0, 0, 0, 0, 0]