### Dynamics model parameters for Dolphin
###
### NOTE: The polynomial coefficients are set in lowest c0 to highest cN.
### NOTE: Clarify coefficient units clearly, avoid unit conversion in code.
###
### Simulation Time Properties
dynamics/diffq_period: 0.001 # Dynamic Simulation integration timestep
dynamics/pub_period: 0.005 # Publish rate set at 200 Hz

### Inertia Properties
dynamics/mass: 0.25
#dynamics/gravity_center: [0.0, 0.0, -0.002] # TODO: fix, should be w.r.t. to rB
dynamics/gravity_center: [0.0, 0.0, 0.0] # TODO: fix, should be w.r.t. to rB
dynamics/buoyancy_center: [0.0, 0.0, 0.0] # TODO: fix this should remain zero but rG should change
dynamics/g: 9.81
dynamics/radius: [.05, .06, .07]
#dynamics/tensor: [0.000000001, 0.0,0.0 , -1e-11, 0.0, 0.0, 0.0, 0.000000001, 0.0]
# Tensor values based on Solidworks values Lxx etc
#dynamics/tensor: [410461.0E-9, 431.0E-9, -11631.0E-9, 431.0E-9, 338994.0E-9, -15.0E-9, -11631.0E-9, -15.0E-9, 546986.0E-9]
##TODO: Remove diagonal override, keep for testing purposes.
dynamics/tensor: [410461.0E-9, 0, 0, 0, 338994.0E-9, 0, 0, 0, 546986.0E-9]

### Damping polynomial coefficients (Velocity to Damping relationship) D(|v|) v: N or Nm
dynamics/damping_ksurge:  [1.29E-02, -7.19E-03, 1.06E+00]  # D(|v|): N
dynamics/damping_ksway:   [-3.07E-03, 8.97E-02, 2.14E+00]  # D(|v|): N
dynamics/damping_kheave:  [3.44E-02, -2.74E-01, 3.75E+00]  # D(|v|): N
# TODO: Use pitch coefficients for now, redo CFD and get cleaner nonzero values curve for roll and yaw
dynamics/damping_kroll:   [-5.76E-04, 1.03E-03, 7.83E-05]  # D(|v|): Nm
dynamics/damping_kpitch:  [-5.76E-04, 1.03E-03, 7.83E-05]  # D(|v|): Nm
dynamics/damping_kyaw:    [-5.76E-04, 1.03E-03, 7.83E-05]  # D(|v|): Nm

dynamics/density: 1000.0
### Actuator Properties
dynamics/num_actuators: 4
#Actuator kF polynomial coefficients (Thrust to Speed relationship) T(n): N(Hz)
dynamics/actuators_kf: [-2.10E-01, 1.68E-03, 1.27E-04]
#Actuator kM polynomial coefficients (Torque to Speed relationship) Tr(n): N.m(Hz)
dynamics/actuators_km: [0, 0, 3.40E-6] # Guestimated from T=Kx^2 where T = 5000g.mm and x =120Hz
#Actuator kV coefficients (Motor Actual Kv Coefficients) n(V): Hz(Volts)
dynamics/actuators_kV: [5.85E+00, 2.25E+01, -1.09E+00]
#Actuators current draw coefficients I(n)
dynamics/actuators_kI: [1.47E+00, 1.62E+01, -5.61E-01, 8.32E-03]
#Actuators acting radius (meters) TODO: VERIFY
dynamics/actuators_radius: .03
#Actuator time constant for first order actuator dynamic model:
dynamics/actuators_tconst: .1
#Inputs higher than actuators_maxsat will saturate to actuators_maxsat
dynamics/actuators_maxsat: 1
#Inputs below actuators_minsat will saturate to actuators_minsat
dynamics/actuators_minsat: -1
# Actuator Direction Inversion
dynamics/actuators_inversion: [1, 1,  -1, -1]
# PWM Range [Min, Mid, Max]
dynamics/actuators_pwm: [1100, 1500, 1900]


### Battery Properties
#Battery discharge rate coefficients : mV
battery/discharge_K: [4.20E+03, -9.69E+00, 1.30E-01, -2.18E-03, 8.00E-05, -8.57E-07]
#LiPo Cell Charged Voltage (Nominal Battery Voltage V) TODO: In simulation, incorporate voltage drop based on currentuse
battery/cell_Vmax: 4.2
#LiPo Cell Cutoff Voltage
battery/cell_Vcut: 3.0
#LiPo Cell ESR
battery/ESR: 0.009
#Battery Cell Count (1n 3.7, 2n 7.4, 3n 11.1V, etc)
battery/cell_n: 2
#Battery Capacity (All Cells)
battery/capacity_mAh: 2200

### Topics
dolphin/dynamics/topic_name: "/dataNavigator"
dolphin/dynamics/external_force_topic: "/dolphin/ForceSensor"
dolphin/dynamics/frame_id: "/shell"

### Initialization
# Meters and Rads [X, Y, Z, Roll, Pitch, Yaw] TODO: Get it back from the other launch file
# TODO: How do I incorporate the vehicle model into the simulation?
dynamics/initial_pose: [-1.0, 1.0, 4.0, 0, 0, 0] #[3.0, 1.1, 2.8, 0, 0, 3.14]
dynamics/initial_velocity: [0, 0, 0, 0, 0, 0]